---
- hosts: localhost
  connection: local
  become: yes

  vars:
    # Where your code lives
    app_dir: "/home/cbtrophy/cbTrophyPi"
    # Where the LED library lives (built in Golden Image)
    matrix_lib_dir: "/home/cbtrophy/rpi-rgb-led-matrix"
    # Your private repo
    firmware_repo: "git@github.com:CrunchyBytesDev/cbTrophyPi.git"

  tasks:
    # --- STAGE 0: HARDWARE SANITIZATION (Critical for LED Matrix) ---

    - name: Permanently disable and unload Pi Sound Module
      block:
        - name: Add sound module to blacklist
          copy:
            dest: /etc/modprobe.d/alsa-blacklist.conf
            content: |
              blacklist snd_bcm2835
              blacklist snd_pcm
              blacklist snd_timer
              blacklist snd
              install snd_bcm2835 /bin/false
            owner: root
            group: root
            mode: '0644'

        - name: Ensure audio is disabled in config.txt
          lineinfile:
            path: /boot/firmware/config.txt
            regexp: '^dtparam=audio='
            line: 'dtparam=audio=off'
          register: config_audio
          # Fallback check if path differs on older DietPi versions
          ignore_errors: yes

        - name: Force unload sound module immediately
          modprobe:
            name: snd_bcm2835
            state: absent
          failed_when: false

    # --- STAGE 1: SYSTEM DEPENDENCIES & NETWORK HANDOVER ---

    - name: Ensure System Dependencies are installed
      apt:
        name:
          - wget
          - git
          - network-manager
          - rfkill
          - build-essential
          - libwebp-dev
          - libwebsockets-dev
          - nlohmann-json3-dev
          - ccache
        state: present
        update_cache: yes

    - name: Ensure NetworkManager is Managing All Devices
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: ifupdown
        option: managed
        value: "true"

    - name: Disable Old Networking Services
      systemd:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop:
        - ifup@wlan0
        - networking
        - wpa_supplicant
      failed_when: false

    - name: Unblock WiFi Radio
      command: rfkill unblock wifi

    # --- STAGE 2: DEPLOY CODE ---

    - name: Clone Private Firmware (As User)
      git:
        repo: "{{ firmware_repo }}"
        dest: "{{ app_dir }}"
        version: main
        accept_hostkey: yes
        force: yes
      become_user: cbtrophy
      register: app_updated

    # --- STAGE 3: ASSET & RUNTIME PREP ---

    - name: Create Image Directories (Outside of Git tracking)
      file:
        path: "{{ item }}"
        state: directory
        owner: cbtrophy
        group: cbtrophy
        mode: '0775'
      loop:
        - "{{ app_dir }}/images"
        - "{{ app_dir }}/images/status"
        - "{{ app_dir }}/images/loop"

    - name: Ensure binary is executable
      file:
        path: "{{ app_dir }}/web_test"
        mode: '0755'
        owner: cbtrophy
        group: cbtrophy

    # --- STAGE 4: FINALIZATION ---

    - name: Reboot if config.txt was changed
      reboot:
        msg: "Rebooting to disable sound modules and finalize hardware setup"
      when: config_audio.changed