---
- hosts: localhost
  connection: local
  become: yes

  vars:
    # Where your code lives
    app_dir: "/home/cbtrophy/cbTrophyPi"
    # Where the LED library lives (built in Golden Image)
    matrix_lib_dir: "/home/cbtrophy/rpi-rgb-led-matrix"
    # Your private repo
    firmware_repo: "git@github.com:CrunchyBytesDev/cbTrophyPi.git"

  tasks:
    # --- STAGE 1: DEPLOY CODE ---
    
    - name: Clone Private Firmware (As User)
      git:
        repo: "{{ firmware_repo }}"
        dest: "{{ app_dir }}"
        version: main
        accept_hostkey: yes
        force: yes
      become_user: cbtrophy
      register: app_updated

    - name: Ensure Wget is Installed
      apt:
        name: wget
        state: present

    # --- STAGE 2: COMPILE C++ ---
    
    - name: Create Makefile for C++ Build
      copy:
        dest: "{{ app_dir }}/Makefile"
        content: |
          CXX=g++
          CXXFLAGS=-Wall -O3 -g -Wextra -Wno-unused-parameter
          # Include path for "led-matrix.h"
          INCLUDES=-I{{ matrix_lib_dir }}/include
          # Linker flags: static LED lib, pthreads, and WebP
          LDFLAGS=-L{{ matrix_lib_dir }}/lib -lrgbmatrix -lrt -lm -lpthread -lwebp -lwebpdemux

          all: trophy_app

          trophy_app: web_test.cc
          	$(CXX) $(CXXFLAGS) $(INCLUDES) web_test.cc -o trophy_app $(LDFLAGS)

          clean:
          	rm -f trophy_app
      become_user: cbtrophy

    - name: Compile Trophy App
      make:
        chdir: "{{ app_dir }}"
      become_user: cbtrophy
      # Force compile if code changed, or if the binary is missing
      when: app_updated.changed or ansible_check_mode
      ignore_errors: no