---
- hosts: localhost
  connection: local
  become: yes

  vars:
    install_dir: "/root/cbTrophy"
    firmware_repo: "git@github.com:CrunchyBytesDev/cbTrophyPi.git"
    ssh_key_path: "/root/.ssh/trophy_key"
    wifi_connect_ver: "4.11.84"

  tasks:
    # --- STAGE 1: SYSTEM PREP ---
    - name: Install System Dependencies
      apt:
        name:
          - python3-pip
          - git
        state: present

    # --- STAGE 2: INSTALL WIFI CONNECT (FIXED FILENAMES) ---
    - name: Detect Architecture
      command: uname -m
      register: cpu_arch

    - name: Set Download Filename (64-bit)
      set_fact:
        wifi_filename: "wifi-connect-aarch64-unknown-linux-gnu.tar.gz"
      when: cpu_arch.stdout == 'aarch64'

    - name: Set Download Filename (32-bit)
      set_fact:
        wifi_filename: "wifi-connect-armv7-unknown-linux-gnueabihf.tar.gz"
      when: cpu_arch.stdout != 'aarch64'

    - name: Download & Install WiFi Connect
      unarchive:
        # Note: The version is in the URL path, but NOT the filename
        src: "https://github.com/balena-os/wifi-connect/releases/download/v{{ wifi_connect_ver }}/{{ wifi_filename }}"
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    - name: Create WiFi Connect Service
      copy:
        dest: /etc/systemd/system/wifi-connect.service
        content: |
          [Unit]
          Description=WiFi Connect Hotspot
          After=NetworkManager.service

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/wifi-connect --portal-ssid "CrunchyBytes-Setup"
          Restart=on-failure
          RestartSec=30

          [Install]
          WantedBy=multi-user.target

    - name: Enable WiFi Connect Service
      systemd:
        name: wifi-connect
        enabled: yes
        daemon_reload: yes

    # --- STAGE 3: PRIVATE FIRMWARE ---
    - name: Clone Private Firmware
      git:
        repo: "{{ firmware_repo }}"
        dest: "{{ install_dir }}"
        version: main
        accept_hostkey: yes
        force: yes
      environment:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i {{ ssh_key_path }}"
      register: firmware_updated

    - name: Compile Firmware
      make:
        chdir: "{{ install_dir }}"
      when: firmware_updated.changed

    # --- STAGE 4: CLEANUP (Disable Old Networking) ---
    # We do this LAST so we don't accidentally kill the connection during the run.
    - name: Disable DietPi/ifupdown Networking
      replace:
        path: /etc/network/interfaces
        regexp: '^(allow-hotplug|iface)'
        replace: '# \1'
      
    - name: Ensure NetworkManager is Enabled
      systemd:
        name: NetworkManager
        enabled: yes
        state: started

  handlers:
    - name: Reboot Pi
      reboot: