---
- hosts: localhost
  connection: local
  become: yes

  vars:
    install_dir: "/root/cbTrophy"
    firmware_repo: "git@github.com:CrunchyBytesDev/cbTrophyPi.git"
    ssh_key_path: "/root/.ssh/trophy_key"
    wifi_connect_ver: "4.11.84"

  tasks:
    # --- STAGE 1: SYSTEM PREP ---
    - name: Install System Dependencies
      apt:
        name:
          - python3-pip
          - git
          - network-manager
          - rfkill
        state: present
        update_cache: yes

    - name: Ensure hostname is set correctly
      hostname:
        name: "{{ ansible_hostname | default('cbTrophy-3873') }}"

    - name: Map hostname to localhost in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ ansible_hostname | default('cbTrophy-3873') }}"
        state: present

    # --- STAGE 2: INSTALL WIFI CONNECT ---
    - name: Detect Architecture
      command: uname -m
      register: cpu_arch

    - name: Set Download Filename
      set_fact:
        wifi_filename: "{{ 'wifi-connect-aarch64-unknown-linux-gnu.tar.gz' if cpu_arch.stdout == 'aarch64' else 'wifi-connect-armv7-unknown-linux-gnueabihf.tar.gz' }}"

    - name: Download & Install WiFi Connect
      unarchive:
        src: "https://github.com/balena-os/wifi-connect/releases/download/v{{ wifi_connect_ver }}/{{ wifi_filename }}"
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    - name: Create WiFi Connect Service
      copy:
        dest: /etc/systemd/system/wifi-connect.service
        content: |
          [Unit]
          Description=WiFi Connect Hotspot
          After=NetworkManager.service

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/wifi-connect --portal-ssid "CrunchyBytes-Setup"
          Restart=on-failure
          RestartSec=30

          [Install]
          WantedBy=multi-user.target

    - name: Enable WiFi Connect Service
      systemd:
        name: wifi-connect
        enabled: yes
        daemon_reload: yes

    # --- STAGE 2.5: INSTALL RGB LED MATRIX LIBRARY ---
    - name: Clone & Build LED Library
      git:
        repo: "https://github.com/hzeller/rpi-rgb-led-matrix.git"
        dest: "/root/rpi-rgb-led-matrix"
        version: master
      register: matrix_lib_updated

    - name: Compile LED Matrix Library
      make:
        chdir: "/root/rpi-rgb-led-matrix"
      when: matrix_lib_updated.changed
      vars:
        ansible_command_timeout: 1200

    # --- STAGE 3: PRIVATE FIRMWARE ---
    - name: Clone Private Firmware
      git:
        repo: "{{ firmware_repo }}"
        dest: "{{ install_dir }}"
        version: main
        accept_hostkey: yes
        force: yes
      environment:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i {{ ssh_key_path }}"
      register: firmware_updated

    - name: Compile Firmware
      make:
        chdir: "{{ install_dir }}"
      when: firmware_updated.changed

    # --- STAGE 4: THE NETWORKING HANDOFF (CORRECTED) ---
    - name: Ensure NetworkManager is Managing All Devices
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: ifupdown
        option: managed
        value: "true"

    - name: Unblock WiFi Radio
      command: rfkill unblock wifi

    - name: Disable Old DietPi Networking Services
      systemd:
        name: "{{ item }}"
        enabled: no
        state: stopped  # It is safe to stop these now because NM is already running
      loop:
        - ifup@wlan0
        - networking    # <-- THIS is the one we missed. This controls the bootup.
      failed_when: false

    - name: Nuke interfaces file
      copy:
        dest: /etc/network/interfaces
        content: "# Network managed by NetworkManager\n"
        force: yes